<template>
  <div class="d-flex flex-column justify-content-around align-items-center">
    <div>
      <div
        v-for="word in words"
        :key="word.step"
        class="d-flex flex-row justify-content-center"
      >
        <div
          v-for="(i, index) in length"
          :key="index"
          style="font-size: 2rem"
          class="char-box d-flex flex-column justify-content-center align-items-center"
          :class="getClass(word.word[index])"
        >
          <template v-if="word.word[index]">
            {{ word.word[index] ? word.word[index].char : "_" }}
          </template>
        </div>
      </div>
    </div>

    <my-keyboard @check="check" v-model:keys="keyboards" class="p-5" />
  </div>
</template>

<script>
import MyKeyboard from "@/components/Keyboard";
import { useToast } from "vue-toastification";

export default {
  setup() {
    // Get toast interface
    const toast = useToast();
    return { toast };
  },
  name: "HelloWorld",
  components: {
    MyKeyboard,
  },
  data() {
    return {
      words: [
        {
          word: [],
          step: 0,
        },
        {
          word: [],
          step: 1,
        },
        {
          word: [],
          step: 2,
        },
        {
          word: [],
          step: 3,
        },
        {
          word: [],
          step: 4,
        },
      ],
      step: 0,
      length: 5,
      solution: null,
      arrayOfSolution: [
        "baker",
        "apple",
        "peach",
        "awake",
        "grade",
        "quiet",
        "total",
        "paste",
        "sleep",
        "queen",
        "silly",
        "smoke",
        "funny",
        "bully",
        "novel",
        "silly",
        "alarm",
        "short",
        "puppy",
        "pizza",
        "anime",
        "await",
        "press",
        "bleep",
        "stuff",
        "email",
        "anger",
        "punch",
        "woman",
        "chess",
        "chain",
        "occur",
        "metro",
        "virus",
        "flask",
        "limbo",
        "omega",
        "feast",
        "drank",
        "freak",
        "which",
        "among",
        "laugh",
        "fault",
        "fifty",
        "skill",
        "knock",
        "speak",
        "stoop",
        "turbo",
        "nomad",
        "empty",
        "reach",
        "agile",
        "apply",
        "timer",
        "shift",
        "canon",
        "gangs",
        "jerky",
        "scrum",
        "cobra",
        "ratio",
        "drama",
        "worse",
        "krill",
        "gypsy",
        "melon",
        "dress",
        "local",
        "kiosk",
        "title",
        "march",
        "brain",
        "whole",
        "hunch",
        "pixel",
        "polar",
        "hotel",
        "sword",
        "cleat",
        "mango",
        "rumba",
        "puffy",
        "filly",
        "billy",
        "leash",
        "clout",
        "dance",
        "ovate",
        "facet",
        "chili",
        "paint",
        "liner",
        "curio",
        "salty",
        "audio",
        "snake",
        "fable",
        "cloak",
        "navel",
        "spurt",
        "pesto",
        "balmy",
        "flash",
        "unwed",
        "early",
        "churn",
        "weedy",
        "stump",
        "lease",
        "witty",
        "wimpy",
        "spoof",
        "saner",
        "blend",
        "salsa",
        "thick",
        "warty",
        "manic",
        "blare",
        "squib",
        "spoon",
        "probe",
        "crepe",
        "knack",
        "force",
        "debut",
        "order",
        "haste",
        "teeth",
        "agent",
        "widen",
        "icily",
        "slice",
        "ingot",
        "clash",
        "juror",
        "blood",
        "abode",
        "throw",
        "unity",
        "pivot",
        "slept",
        "troop",
        "spare",
        "sewer",
        "parse",
        "morph",
        "cacti",
        "tacky",
        "spool",
        "demon",
        "moody",
        "annex",
        "begin",
        "fuzzy",
        "patch",
        "water",
        "lumpy",
        "admin",
        "omega",
        "limit",
        "tabby",
        "macho",
        "aisle",
        "skiff",
        "basis",
        "plank",
        "verge",
        "botch",
        "crawl",
        "lousy",
        "slain",
        "cubic",
        "raise",
        "wrack",
        "guide",
        "foist",
        "cameo",
        "under",
        "actor",
        "revue",
        "fraud",
        "harpy",
        "scoop",
        "climb",
        "refer",
        "olden",
        "clerk",
        "debar",
        "tally",
        "ethic",
        "cairn",
        "tulle",
        "ghoul",
        "hilly",
        "crude",
        "apart",
        "scale",
        "older",
        "plain",
        "sperm",
        "briny",
        "abbot",
        "rerun",
        "quest",
        "crisp",
        "bound",
        "befit",
        "drawn",
        "suite",
        "itchy",
        "cheer",
        "bagel",
        "guess",
        "broad",
        "axiom",
        "chard",
        "caput",
        "leant",
        "harsh",
        "curse",
        "proud",
        "swing",
        "opine",
        "taste",
        "lupus",
        "gumbo",
        "miner",
        "green",
        "chasm",
        "lipid",
        "topic",
        "armor",
        "brush",
        "crane",
        "mural",
        "abled",
        "habit",
        "bossy",
        "maker",
        "dusky",
        "dizzy",
        "lithe",
        "brook",
        "jazzy",
        "fifty",
        "sense",
        "giant",
        "surly",
        "legal",
        "fatal",
        "flunk",
        "began",
        "prune",
        "small",
        "slant",
        "scoff",
        "torus",
        "ninny",
        "covey",
        "viper",
        "taken",
        "moral",
        "vogue",
        "owing",
        "token",
        "entry",
        "booth",
        "voter",
        "chide",
        "elfin",
        "ebony",
        "neigh",
        "minim",
        "melon",
        "kneed",
        "decoy",
        "voila",
        "ankle",
        "arrow",
        "mushy",
        "tribe",
        "cease",
        "eager",
        "birth",
        "graph",
        "odder",
        "terra",
        "weird",
        "tried",
        "clack",
        "color",
        "rough",
        "weigh",
        "uncut",
        "ladle",
        "strip",
        "craft",
        "minus",
        "dicey",
        "titan",
        "lucid",
        "vicar",
        "dress",
        "ditch",
        "gypsy",
        "pasta",
        "taffy",
        "flame",
        "swoop",
        "aloof",
        "sight",
        "broke",
        "teary",
        "chart",
        "sixty",
        "wordy",
        "sheer",
        "leper",
        "nosey",
        "bulge",
        "savor",
        "clamp",
        "funky",
        "foamy",
        "toxic",
        "brand",
        "plumb",
        "dingy",
        "butte",
        "drill",
        "tripe",
        "bicep",
        "tenor",
        "krill",
        "worse",
        "drama",
        "hyena",
        "think",
        "ratio",
        "cobra",
        "basil",
        "scrum",
        "bused",
        "phone",
        "court",
        "camel",
        "proof",
        "heard",
        "angel",
        "petal",
        "pouty",
        "throb",
        "maybe",
        "fetal",
        "sprig",
        "spine",
        "shout",
        "cadet",
        "macro",
        "dodgy",
        "satyr",
        "rarer",
        "binge",
        "trend",
        "nutty",
        "leapt",
        "amiss",
        "split",
        "myrrh",
        "width",
        "sonar",
        "tower",
        "baron",
        "fever",
        "waver",
        "spark",
        "belie",
        "sloop",
        "expel",
        "smote",
        "baler",
        "above",
        "north",
        "wafer",
        "scant",
        "frill",
        "awash",
        "snack",
        "scowl",
        "frail",
        "drift",
        "limbo",
        "fence",
        "motel",
        "ounce",
        "wreak",
        "revel",
        "talon",
        "prior",
        "knelt",
        "cello",
        "flake",
        "debug",
        "anode",
        "crime",
        "salve",
        "scout",
        "imbue",
        "pinky",
        "stave",
        "vague",
        "chock",
        "fight",
        "video",
        "stone",
        "teach",
        "cleft",
        "frost",
        "prawn",
        "booty",
        "twist",
        "apnea",
        "stiff",
        "plaza",
        "ledge",
        "tweak",
        "board",
        "grant",
        "medic",
        "bacon",
        "cable",
        "brawl",
        "slunk",
        "raspy",
        "forum",
        "drone",
        "women",
        "mucus",
        "boast",
        "toddy",
        "coven",
        "tumor",
        "truer",
        "wrath",
        "stall",
        "steam",
        "axial",
        "purer",
        "daily",
        "trail",
        "niche",
        "mealy",
        "juice",
        "nylon",
        "plump",
        "merry",
        "flail",
        "papal",
        "wheat",
        "berry",
        "cower",
        "erect",
        "brute",
        "leggy",
        "snipe",
        "sinew",
        "skier",
        "penny",
        "jumpy",
        "rally",
        "umbra",
        "scary",
        "modem",
        "gross",
        "avian",
        "greed",
        "satin",
        "tonic",
        "parka",
        "sniff",
        "livid",
        "stark",
        "trump",
        "giddy",
        "reuse",
        "taboo",
        "avoid",
        "quote",
        "devil",
        "liken",
        "gloss",
        "gayer",
        "beret",
        "noise",
        "gland",
        "dealt",
        "sling",
        "rumor",
        "opera",
        "thigh",
        "tonga",
        "flare",
        "wound",
        "white",
        "bulky",
        "etude",
        "horse",
        "circa",
        "paddy",
        "inbox",
        "fizzy",
        "grain",
        "exert",
        "surge",
        "gleam",
        "belle",
        "salvo",
        "crush",
        "fruit",
        "sappy",
        "taker",
        "tract",
        "ovine",
        "spiky",
        "frank",
        "reedy",
        "filth",
        "spasm",
        "heave",
        "mambo",
        "right",
        "clank",
        "trust",
        "lumen",
        "borne",
        "spook",
        "sauce",
        "amber",
        "lathe",
        "carat",
        "corer",
        "dirty",
        "slyly",
        "affix",
        "alloy",
        "taint",
        "sheep",
        "kinky",
        "wooly",
        "mauve",
        "flung",
        "yacht",
        "fried",
        "quail",
        "brunt",
        "grimy",
        "curvy",
        "cagey",
        "rinse",
        "deuce",
        "state",
        "grasp",
        "milky",
        "bison",
        "graft",
        "sandy",
        "baste",
        "flask",
        "hedge",
        "girly",
        "swash",
        "boney",
        "coupe",
        "endow",
        "abhor",
        "welch",
        "blade",
        "tight",
        "geese",
        "miser",
        "mirth",
        "cloud",
        "cabal",
        "leech",
        "close",
        "tenth",
        "pecan",
        "droit",
        "grail",
        "clone",
        "guise",
        "ralph",
        "tango",
        "biddy",
        "smith",
        "mower",
        "payee",
        "serif",
        "drape",
        "fifth",
        "spank",
        "glaze",
        "allot",
        "truck",
        "kayak",
        "virus",
        "testy",
        "tepee",
        "fully",
        "zonal",
        "metro",
        "curry",
        "grand",
        "banjo",
        "axion",
        "bezel",
        "occur",
        "chain",
        "nasal",
        "gooey",
        "filer",
        "brace",
        "allay",
        "pubic",
        "raven",
        "plead",
        "gnash",
        "flaky",
        "munch",
        "dully",
        "eking",
        "thing",
        "slink",
        "hurry",
        "theft",
        "shorn",
        "pygmy",
        "ranch",
        "wring",
        "lemon",
        "shore",
        "mamma",
        "froze",
        "newer",
        "style",
        "moose",
        "antic",
        "drown",
        "vegan",
        "chess",
        "guppy",
        "union",
        "lever",
        "lorry",
        "image",
        "cabby",
        "druid",
        "exact",
        "truth",
        "dopey",
        "spear",
        "cried",
        "chime",
        "crony",
        "stunk",
        "timid",
        "batch",
        "gauge",
        "rotor",
        "crack",
        "curve",
        "latte",
        "witch",
        "bunch",
        "repel",
        "anvil",
        "soapy",
        "meter",
        "broth",
        "madly",
        "dried",
        "scene",
        "known",
        "magma",
        "roost",
        "woman",
        "thong",
        "punch",
        "pasty",
        "downy",
        "knead",
        "whirl",
        "rapid",
        "clang",
        "anger",
        "drive",
        "goofy",
        "email",
        "music",
        "stuff",
        "bleep",
        "rider",
        "mecca",
        "folio",
        "setup",
        "verso",
        "quash",
        "fauna",
        "gummy",
        "happy",
        "newly",
        "fussy",
        "relic",
        "guava",
        "ratty",
        "fudge",
        "femur",
        "chirp",
        "forte",
        "alibi",
        "whine",
        "petty",
        "golly",
        "plait",
        "fleck",
        "felon",
        "gourd",
        "brown",
        "thrum",
        "ficus",
        "stash",
        "decry",
        "wiser",
        "junta",
        "visor",
        "daunt",
        "scree",
        "impel",
        "await",
        "press",
        "whose",
        "turbo",
        "stoop",
        "speak",
        "mangy",
        "eying",
        "inlet",
        "crone",
        "pulse",
        "mossy",
        "staid",
        "hence",
        "pinch",
        "teddy",
        "sully",
        "snore",
        "ripen",
        "snowy",
        "attic",
        "going",
        "leach",
        "mouth",
        "hound",
        "clump",
        "tonal",
        "bigot",
        "peril",
        "piece",
        "blame",
        "haute",
        "spied",
        "undid",
        "intro",
        "basal",
        "shine",
        "gecko",
        "rodeo",
        "guard",
        "steer",
        "loamy",
        "scamp",
        "scram",
        "manly",
        "hello",
        "vaunt",
        "organ",
        "feral",
        "knock",
        "extra",
        "condo",
        "adapt",
        "willy",
        "polka",
        "rayon",
        "skirt",
        "faith",
        "torso",
        "match",
        "mercy",
        "tepid",
        "sleek",
        "riser",
        "twixt",
        "peace",
        "flush",
        "catty",
        "login",
        "eject",
        "roger",
        "rival",
        "untie",
        "refit",
        "aorta",
        "adult",
        "judge",
        "rower",
        "artsy",
        "rural",
        "shave",
      ],
      keyboards: [
        { char: "q", notCorrect: false },
        { char: "w", notCorrect: false },
        { char: "e", notCorrect: false },
        { char: "r", notCorrect: false },
        { char: "t", notCorrect: false },
        { char: "y", notCorrect: false },
        { char: "u", notCorrect: false },
        { char: "i", notCorrect: false },
        { char: "o", notCorrect: false },
        { char: "p", notCorrect: false },
        { char: "a", notCorrect: false },
        { char: "s", notCorrect: false },
        { char: "d", notCorrect: false },
        { char: "f", notCorrect: false },
        { char: "g", notCorrect: false },
        { char: "h", notCorrect: false },
        { char: "j", notCorrect: false },
        { char: "k", notCorrect: false },
        { char: "l", notCorrect: false },
        { char: "enter", notCorrect: false },
        { char: "z", notCorrect: false },
        { char: "x", notCorrect: false },
        { char: "c", notCorrect: false },
        { char: "v", notCorrect: false },
        { char: "b", notCorrect: false },
        { char: "n", notCorrect: false },
        { char: "m", notCorrect: false },
        { char: "delete", notCorrect: false },
      ],
    };
  },
  mounted() {
    const solution = JSON.parse(localStorage.getItem("solution"));
    if (solution) {
      this.solution = solution;
    } else {
      this.solution =
        this.arrayOfSolution[
          Math.floor(Math.random() * this.arrayOfSolution.length)
        ];
      localStorage.setItem("solution", JSON.stringify(this.solution));
    }

    const suggestion = JSON.parse(localStorage.getItem("suggestion"));
    if (suggestion && suggestion.length) {
      suggestion.forEach((i, index) => {
        const splitWord = i.split("");
        splitWord.forEach((j) => {
          this.words[index].word.push({
            char: j,
            correct: false,
            exist: false,
          });
        });

        // this.step = index
        this.findWord(this.words[index]);
      });
    }
  },
  methods: {
    check(input) {
      const findStep = this.words.find((i) => i.step == this.step);
      if (findStep) {
        if (findStep.word.length < this.length) {
          if (input == "delete") {
            findStep.word.pop();
          } else if (input !== "enter" && input !== "delete") {
            const sample = {
              char: input,
              correct: false,
              exist: false,
            };

            findStep.word.push(sample);
          }
        } else if (findStep.word.length == this.length && input === "enter") {
          this.findWord(findStep, true);
        } else if (input == "delete") {
          findStep.word.pop();
        }
      }
    },

    findWord(findStep, set) {
      // check word is in array of solution
      const word = findStep.word.map((i) => i.char).join("");
      if (!this.arrayOfSolution.includes(word)) {
        return this.toast("Not in word list");
      }

      let solution = this.solution.split("");

      findStep.word.forEach((i, index) => {
        if (i.char == this.solution[index]) {
          i.correct = true;
          solution[index] = "-";
        }
      });

      findStep.word.forEach((i) => {
        if (!i.correct && solution.includes(i.char)) {
          i.exist = true;
          const index = solution.indexOf(i.char);
          solution[index] = "-";
        }
      });

      solution = solution.join("");

      findStep.word.forEach((i) => {
        if (!this.solution.includes(i.char)) {
          const findKey = this.keyboards.find((key) => key.char == i.char);
          findKey.notCorrect = true;
        }
      });
      if (set) {
        this.setItem(word);
      }
      // else finish the game

      if (solution == "-".repeat(this.length)) {
        this.finishGame();
        return this.toast.success("WINNER");
      } else if (this.step == 4) {
        this.finishGame();
        return this.toast.danger("YOU ARE LOSER");
      }
      this.step++;
    },
    finishGame() {
      localStorage.removeItem("suggestion");
      localStorage.removeItem("solution");
      this.step = 5;
    },
    setItem(word) {
      const suggestion = JSON.parse(localStorage.getItem("suggestion")) || [];
      localStorage.setItem("suggestion", JSON.stringify([...suggestion, word]));
    },
    getClass(word) {
      if (word) {
        if (word.correct) return "bg-success";
        else if (word.exist) return "bg-warning";
      }
    },
  },
};
</script>
